### ISSUE TITLE
Add nbgitpuller

### ISSUE THREAD

**Issue by riazarbi** [cityofcapetown/docker_datascience#30]
The datascience_training repo relies on nbgitpuller to be pulled automatically into a user's home directory. 

For reasons why you would want to use nbgitpuller over straight git, see [here.](https://jupyterhub.github.io/nbgitpuller/topic/automatic-merging.html)

I have added and gotten nbgitpuller working for the R images - see [here.](https://github.com/riazarbi/jupyter-rstudio-proxy/blob/7832fad4a0e3a53ff950bdb52e630a9af4e5fb3e/r-base/Dockerfile#L192)

Please could you add similar functionality to the python images?

**Comment by riazarbi** [comment]
To add to this - if you DONT have nbgitpuller spawn fails. Because of this, I will revert this functionality for all images.

nbgitpuller needs to work so that we can implement this for all environments - so could we upgrade this to urgent?

![image](https://user-images.githubusercontent.com/13433911/65141682-6973b280-da11-11e9-8803-d4666bc8a3ea.png)

**Comment by Gordonei** [comment]
OK, added `nbgitpuller` - I presume the requisite setting for pulling the repo on spawn is in `sandbox-values.yaml`?

**Comment by riazarbi** [comment]
Just copy the nbgitpuller command from the R image section of the yaml.

**Comment by riazarbi** [comment]
Assuming this works now
