### ISSUE TITLE
Allow ODBC connections without --net="host" flag

### ISSUE THREAD

**Issue by riazarbi** [cityofcapetown/docker_datascience#7]
# Issue

At present a container can only talk to a remote ODBC connection if the `--net="host"` flag is set. This is less secure than default

# Solution

Find a way to allow remote ODBC connection without giving a container access to the entire host network stack

# Priority

Moderate; not urgent

# More Detail

As per - 

https://docs.docker.com/engine/reference/run/#network-settings

```
Note: --network="host" gives the container full access to local system services such as D-bus and is therefore considered insecure.
```

**Comment by Gordonei** [comment]
This is actually down to dodgy Docker networking - the easiest thing to do is make sure that the only networking connection you're using at the time is the one that has access to the port you're interested in.
